# Parameters for DVC pipeline

# Parameters specific to the problem to solve
problem: 'pcvrp'
problem_params:
  PRICE_MODE: 0

# Metric file
metric_file: 'scores/scores.json'

# Training parameters
seed: 1234
eval_only: false
no_cuda: false
cuda: 0
run_name: 'run'
graph_size: 20
batch_size: 512
epoch_size: 512     # 1280000
val_size: 10000
val_dataset: null
eval_batch_size: 1024
checkpoint_encoder: false
data_distribution: 'saturn'
log_step: 50
epoch_start: 0
checkpoint_epochs: 1
load_path: null
resume: null
no_tensorboard: false
no_progress_bar: false
high_value: 0.5

# Model parameters
model: 'attention'
embedding_dim: 128
hidden_dim: 128
n_encode_layers: 3
tanh_clipping: 10
normalization: 'batch'
lr_model: 1.0e-4
lr_critic: 1.0e-4
lr_decay: 1.0
n_epochs: 1
max_grad_norm: 1.0
exp_beta: 0.8
baseline: 'rollout'
bl_alpha: 0.05
bl_warmup_epochs: null
shrink_size: null
